<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel = "stylesheet"
          type = "text/css"
          href = "css/navigationsbar.css" />

    <title>Johannes Fog</title>
</head>
<body>

<div class="row">

<!-- Start Picture -->
    <div class="col">
        <img src="./Images/johannesfog.png" alt="logo">
    </div>
<!-- Overskrift -->
    <div class="col">
        <h1 text-center> Johannes Fog - Trælast & Byggecenter</h1>
    </div>

</div>

<!-- Navigationsbar -->
<div class="topnav">
    <a class="active" href="FrontController?target=redirect&destination=index">Home</a>
    <a href= "FrontController?target=redirect&destination=about"">About FOG</a>
    <a href="FrontController?target=redirect&destination=custom">Carports</a>
    <a href="FrontController?target=redirect&destination=basket">Basket</a>
</div>